= Timbuctoo default GUI

This project contains a few javascript applications that allow you to do some sensible things with timbuctoo.

 * A generic edit client that will use the timbuctoo provided metadata to render a basic editing form
 * A generic search client that will generate a search interface based on the metadata that timbuctoo and solr provide. It is tested with the timbuctoo-faceted-search-indexer
 * A multicollection search client. Which is similar to the previous one, but instead of searching one dataset, you search through all of them at once
 * An upload GUI and start page that provides an entry point to the other GUI's and allows you to upload data into timbuctoo

= build

There should be an image called *huygensing/timbuctoo-gui:buildbase* on dockerhub.
This image contains everything to rebuild the gui files (including all dependencies).

To regenerate this image you run `docker build -t huygensing/timbuctoo-gui:buildbase -f Dockerfile.buildbase .`

To build a container with the runtime you run `docker build -t huygensing/timbuctoo-gui .`.
This container will expose a webserver on port 80 that hosts the html and js files.
You can set the environment variables listed in the Dockerfile to specify the urls that the gui uses.


= develop

run `docker-compose up -d` to run all the services. 
This will also run a watcher process inside the timbuctoo-gui container so that any changes you make in the files in this repo will be automatically rebuilt on the container.
We don't run browsersync so you still need to manually refresh your browser.
