g.V()
.has("isLatest", true)
.filter {
  it.get()
    .property("types")
    .value()
    .contains("\"wwperson\"")
}.as("or")
.or(__.and(__.outE("hasBirthPlace")
    .otherV()
    .as("or|0|and|0|or")
    .or(__())
    .union(__()
      .as("or|0|and|0|or|0")))
  .union(__.outE("hasBirthPlace")
    .as("or|0|and|0")
    .otherV()
    .as("or|0|and|0|or")
    .or(__())
    .union(__()
      .as("or|0|and|0|or|0"))
    .as("or|0|0")))
.union(

  __()
  .as("or|0")
  .and(__.outE("hasBirthPlace")
    .otherV()
    .as("or|0|and|0|or")
    .or(__())
    .union(__()
      .as("or|0|and|0|or|0")))
  .union(__.outE("hasBirthPlace")
    .as("or|0|and|0")
    .otherV()
    .as("or|0|and|0|or")
    .or(__())
    .union(__()
      .as("or|0|and|0|or|0"))
    .as("or|0|0")))

.select("or", "or|0")