export default {
   UPLOADING: "UPLOADING",
   MAPPING_CREATION: "MAPPING_CREATION",
   MAPPING_EXECUTION: "MAPPING_EXECUTION",
   MAPPING_CREATION_AFTER_ERRORS: "MAPPING_CREATION_AFTER_ERRORS",
   AVAILABLE: "AVAILABLE"
}